import type { Product } from "@/types/database";

const NOW = "2026-05-07T00:00:00.000Z";

function p(input: Partial<Product> & Pick<Product, "id" | "name" | "category" | "price" | "sku" | "images">): Product {
  return {
    description: null,
    scale: "1:18",
    brand: null,
    stock: 6,
    features: {},
    is_limited_edition: false,
    is_featured: true,
    condition: "mint",
    rating: 4.7,
    review_count: 12,
    created_at: NOW,
    updated_at: NOW,
    ...input,
  };
}

const FEATURED: Product[] = [
  p({
    id: "mk-aventador",
    name: "Lamborghini Aventador SVJ",
    description: "Hand-finished metallic paint, working scissor doors, detailed V12 engine bay.",
    category: "cars",
    scale: "1:18",
    brand: "Bburago",
    price: 78.5,
    stock: 4,
    sku: "BB-AVNT-SVJ-118",
    images: ["https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=1200&q=80"],
    rating: 4.8,
    review_count: 24,
  }),
  p({
    id: "mk-911-gt3",
    name: "Porsche 911 GT3 RS — Weissach Pkg",
    description: "Limited rendering of the track-focused 992-generation 911 GT3 RS.",
    category: "cars",
    scale: "1:18",
    brand: "Minichamps",
    price: 165.0,
    stock: 2,
    sku: "MC-911-GT3RS-118",
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 5,
    review_count: 9,
  }),
  p({
    id: "mk-747",
    name: "Boeing 747-8 Lufthansa",
    description: "Commercial aviation icon. Authentic Lufthansa livery, retractable landing gear.",
    category: "planes",
    scale: "1:18",
    brand: "Herpa Wings",
    price: 92,
    stock: 6,
    sku: "HW-747-LH-1200",
    images: ["https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=80"],
    rating: 4.6,
    review_count: 18,
  }),
  p({
    id: "mk-volvo",
    name: "Volvo FH16 Globetrotter Reefer",
    description: "European long-haul tractor with detailed cabin interior.",
    category: "trucks",
    scale: "1:43",
    brand: "Tekno",
    price: 124,
    stock: 3,
    sku: "TK-VOLVO-FH16-143",
    images: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 4.9,
    review_count: 6,
  }),
  p({
    id: "mk-ducati",
    name: "Ducati Panigale V4 R",
    description: "Track-focused superbike with carbon fiber details.",
    category: "bikes",
    scale: "1:12",
    brand: "Maisto",
    price: 42,
    stock: 12,
    sku: "MS-DUC-V4R-112",
    images: ["https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&q=80"],
    rating: 4.4,
    review_count: 22,
  }),
  p({
    id: "mk-bugatti",
    name: "Bugatti Chiron Super Sport 300+",
    description: "World-record breaking hypercar in immaculate detail.",
    category: "cars",
    scale: "1:43",
    brand: "AutoArt",
    price: 245,
    stock: 1,
    sku: "AA-CHIRON-300-143",
    images: ["https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 5,
    review_count: 4,
  }),
  p({
    id: "mk-concorde",
    name: "Concorde — Air France",
    description: "Supersonic jet legend in retired Air France livery.",
    category: "planes",
    scale: "1:18",
    brand: "Herpa Wings",
    price: 178,
    stock: 2,
    sku: "HW-CONC-AF-1200",
    images: ["https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 4.9,
    review_count: 7,
  }),
  p({
    id: "mk-bmw-m1000",
    name: "BMW M1000RR Superbike",
    description: "Bavarian engineering meets racing pedigree. M Carbon wheels.",
    category: "bikes",
    scale: "1:12",
    brand: "Minichamps",
    price: 89,
    stock: 5,
    sku: "MC-BMW-M1000-112",
    images: ["https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 4.8,
    review_count: 5,
  }),
];

export const MOCK_PRODUCTS = {
  featured: FEATURED,
  limited: FEATURED.filter((x) => x.is_limited_edition).slice(0, 2),
};
