import type { Product, ProductCategory } from "@/types/database";

const NOW = "2026-05-07T00:00:00.000Z";

function p(input: Partial<Product> & Pick<Product, "id" | "name" | "category" | "price" | "sku" | "images">): Product {
  return {
    description: null,
    scale: "1:18",
    brand: null,
    stock: 6,
    features: {},
    is_limited_edition: false,
    is_featured: true,
    condition: "mint",
    rating: 4.7,
    review_count: 12,
    created_at: NOW,
    updated_at: NOW,
    ...input,
  };
}

const FEATURED: Product[] = [
  p({
    id: "mk-aventador",
    name: "Lamborghini Aventador SVJ",
    description: "Hand-finished metallic paint, working scissor doors, detailed V12 engine bay.",
    category: "cars",
    scale: "1:18",
    brand: "Bburago",
    price: 78.5,
    stock: 4,
    sku: "BB-AVNT-SVJ-118",
    images: ["https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=1200&q=80"],
    rating: 4.8,
    review_count: 24,
  }),
  p({
    id: "mk-911-gt3",
    name: "Porsche 911 GT3 RS — Weissach Pkg",
    description: "Limited rendering of the track-focused 992-generation 911 GT3 RS.",
    category: "cars",
    scale: "1:18",
    brand: "Minichamps",
    price: 165.0,
    stock: 2,
    sku: "MC-911-GT3RS-118",
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 5,
    review_count: 9,
  }),
  p({
    id: "mk-bugatti",
    name: "Bugatti Chiron Super Sport 300+",
    description: "World-record breaking hypercar in immaculate detail.",
    category: "cars",
    scale: "1:43",
    brand: "AutoArt",
    price: 245,
    stock: 1,
    sku: "AA-CHIRON-300-143",
    images: ["https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 5,
    review_count: 4,
  }),
  p({
    id: "mk-747",
    name: "Boeing 747-8 Lufthansa",
    description: "Commercial aviation icon. Authentic Lufthansa livery, retractable landing gear.",
    category: "planes",
    scale: "1:18",
    brand: "Herpa Wings",
    price: 92,
    stock: 6,
    sku: "HW-747-LH-1200",
    images: ["https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=80"],
    rating: 4.6,
    review_count: 18,
  }),
  p({
    id: "mk-concorde",
    name: "Concorde — Air France",
    description: "Supersonic jet legend in retired Air France livery.",
    category: "planes",
    scale: "1:18",
    brand: "Herpa Wings",
    price: 178,
    stock: 2,
    sku: "HW-CONC-AF-1200",
    images: ["https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 4.9,
    review_count: 7,
  }),
  p({
    id: "mk-f22",
    name: "F-22 Raptor Stealth Fighter",
    description: "USAF air superiority fighter. Removable canopy, articulating thrust-vector nozzles.",
    category: "planes",
    scale: "1:24",
    brand: "Hobby Master",
    price: 58,
    stock: 8,
    sku: "HM-F22-124",
    images: ["https://images.unsplash.com/photo-1583373834259-46cc92173cb7?w=1200&q=80"],
    rating: 4.7,
    review_count: 11,
  }),
  p({
    id: "mk-volvo",
    name: "Volvo FH16 Globetrotter Reefer",
    description: "European long-haul tractor with detailed cabin interior.",
    category: "trucks",
    scale: "1:43",
    brand: "Tekno",
    price: 124,
    stock: 3,
    sku: "TK-VOLVO-FH16-143",
    images: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 4.9,
    review_count: 6,
  }),
  p({
    id: "mk-actros",
    name: "Mercedes-Benz Actros 5",
    description: "Modern flagship truck with photorealistic livery, detailed Stage V engine.",
    category: "trucks",
    scale: "1:43",
    brand: "Eligor",
    price: 95,
    stock: 5,
    sku: "EL-ACTROS5-143",
    images: ["https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?w=1200&q=80"],
    rating: 4.5,
    review_count: 14,
  }),
  p({
    id: "mk-scania",
    name: "Scania R730 V8 Topline",
    description: "European truck show champion. Premium Swedish detailing, chrome accessories.",
    category: "trucks",
    scale: "1:24",
    brand: "Italeri",
    price: 68,
    stock: 7,
    sku: "IT-SCANIA-R730-124",
    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&q=80"],
    rating: 4.6,
    review_count: 9,
  }),
  p({
    id: "mk-ducati",
    name: "Ducati Panigale V4 R",
    description: "Track-focused superbike with carbon fiber details.",
    category: "bikes",
    scale: "1:12",
    brand: "Maisto",
    price: 42,
    stock: 12,
    sku: "MS-DUC-V4R-112",
    images: ["https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&q=80"],
    rating: 4.4,
    review_count: 22,
  }),
  p({
    id: "mk-bmw-m1000",
    name: "BMW M1000RR Superbike",
    description: "Bavarian engineering meets racing pedigree. M Carbon wheels.",
    category: "bikes",
    scale: "1:12",
    brand: "Minichamps",
    price: 89,
    stock: 5,
    sku: "MC-BMW-M1000-112",
    images: ["https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&q=80"],
    is_limited_edition: true,
    condition: "sealed",
    rating: 4.8,
    review_count: 5,
  }),
  p({
    id: "mk-fatboy",
    name: "Harley-Davidson Fat Boy",
    description: "Iconic American cruiser with chromed engine, leather-effect saddle.",
    category: "bikes",
    scale: "1:18",
    brand: "Maisto",
    price: 28.5,
    stock: 18,
    sku: "MS-HD-FATBOY-118",
    images: ["https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1200&q=80"],
    rating: 4.2,
    review_count: 31,
  }),
];

const byCategory = (cat: ProductCategory) => FEATURED.filter((x) => x.category === cat);

export const MOCK_PRODUCTS = {
  featured: FEATURED,
  limited: FEATURED.filter((x) => x.is_limited_edition),
  cars: byCategory("cars"),
  planes: byCategory("planes"),
  trucks: byCategory("trucks"),
  bikes: byCategory("bikes"),
};
